version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    env_file:
      - ./.env
    environment:
      cluster.name: efk-cluster
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    container_name: kibana
    env_file:
      - ./.env
   # volumes:
     # - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      elasticsearch.hosts: '["http://elasticsearch:9200"]'
     # elasticsearch.username: kibana_system
     # elasticsearch.password: ${KIBANA_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - filebeat

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.2
    container_name: filebeat
    env_file:
      - ./.env
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      # требуется для доступа к дополнительной информации о контейнерах
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # требуется для доступа ко всем журналам docker (только для чтения):
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    user: root
    #environment:
      #ELASTICSEARCH_USERNAME: elastic
      #ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch