filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml #?
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # искать docker контейнер
    - type: docker
      labels.dedot: true #?
      templates:
        - condition:
            equals:
              docker.container.labels.collect_logs_with_filebeat: "true" #?
            contains:
              # имя которого fastapi_app
              docker.container.name: fastapi_app
          # определим конфигурацию сбора для этого контейнера
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
          processors:
           - decode_json_fields:
              when.equals:
                docker.container.labels.decode_logs_event_to_json_object: "true"
                fields: ["message"]
                target: ""
                max_depth: 8
                overwrite_keys: true
           - add_docker_metadata: ~

# Лог сообщения передаем в эластик серч
output.elasticsearch:
  protocol: "https"
  hosts: ["192.168.204.132:9200"]
  username: 'elastic'
  password: 'elastic'
  ssl.certificate_authorities: "/mnt/cert/http_ca.crt"
setup.kibana:
  host: "192.168.204.132:5601"