# Включить перезагрузку конфигурации filebeat
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# Автообнаружение позволяет обнаруживать изменения в системе и создавать новые модули
# или входные данные, когда они происходят.
filebeat.autodiscover:
  providers:
    # искать docker контейнер
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            equals:
              docker.container.labels.collect_logs_with_filebeat: "true"
          # определим конфигурацию сбора для этого контейнера
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
          processors:
           - decode_json_fields:
              when.equals:
                docker.container.labels.decode_logs_event_to_json_object: "true"
                fields: ["message"]
                target: ""
                max_depth: 8
                overwrite_keys: true
           - add_docker_metadata: ~

# Какие выходные данные использовать при отправке данных, собранных beat.
output.elasticsearch:
  protocol: "https"
  hosts: ["elasticsearch:9200"]
  username: 'elastic'
  password: 'elastic'
setup.kibana:
  host: "kibana:5601"