version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    ports:
      - "9091:8080"
      - "9092:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker