tag = "${env.BUILD_NUMBER}"
git_clone_url = "http://labvm-42-05.itmo-lab.cosm-lab.science/team-7/monster-backend.git"
registry_host = "https://registry.hub.docker.com"

def build(image_name, path) {
    image = docker.build("cherrywood69/monster-company/${image_name}:${tag}", "-f ./${path}/Dockerfile ./${path}")
    return image
}

def build_eureka_server() {
    return build("eureka-server", "./eureka-server")
}

def build_config_server() {
    return build("config-server", "./config-server")
}

def build_auth_facade() {
    return build("auth-facade", "./auth-endpoint-aggregator")
}

def build_auth_reactive_facade() {
    return build("auth-reactive-facade", "./reactive-auth-endpoint-aggregator")
}

def build_user_service() {
    return build("user-service", "./user-service")
}

def build_child_service() {
    return build("child-service", "./child-service")
}

def build_infection_service() {
    return build("infection-service", "./infection-service")
}

def build_monster_service() {
    return build("monster-service", "./monster-service")
}

def build_gateway_service() {
    return build("gateway-service", "./gateway-service")
}

def push_image(image) {
    docker.withRegistry("${registry_host}", 'dockerhub_cherrywood') {
        image.push()
        image.push("latest")
    }
}

def deploy(image) {
    sh "docker-compose -f docker-compose.yml pull ${image}"
    sh "docker-compose -f docker-compose.yml up -d ${image}"
}

node {
    git credentialsId: 'gitlab_cherrywood', url: "${git_clone_url}", branch: 'jenkins'

    def eureka
    def config
    def facade
    def reactive_facade
    def user
    def child
    def infection
    def monster
    def gateway

    stage('Build') {
        eureka = build_eureka_server()
        //config = build_config_server()
        //facade = build_auth_facade()
        //reactive_facade = build_auth_reactive_facade()
        //user = build_user_service()
        //child = build_child_service()
        //infection = build_infection_service()
        //monster = build_monster_service()
        //gateway = build_gateway_service()
    }
    stage('Push') {
        push_image(eureka)
        //push_image(config)
        //push_image(facade)
        //push_image(reactive_facade)
        //push_image(user)
        //push_image(child)
        //push_image(infection)
        //push_image(monster)
       // push_image(gateway)
    }
    if (currentBuild.currentResult == 'SUCCESS') {
        stage('Deploy') {

            //deploy("eureka")
            //deploy("config")
            //deploy("facade")
            //deploy("reactive_facade")
           // deploy("user")
            //deploy("child")
            //deploy("infection")
            //deploy("monster")
           // deploy("gateway")
        }
    }
}