version: "3.7"

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    container_name: $POSTGRES_HOST
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres/db:/var/lib/postgresql/data