spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: spring

#3
management:
  endpoints:
    web:
      exposure:
        include: *
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          push-rate: 5s
          base-url: 172.17.01:9091
          grouping-key:
            application: ${spring.application.name}
            instance: ${spring.application.name}:${server.port}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}
