spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:monster_company}?currentSchema=infection
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345}
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: infection

server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#3
management:
  endpoints:
    web:
      exposure:
        include: *
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          push-rate: 5s
          base-url: 172.17.01:9091
          grouping-key:
            application: ${spring.application.name}
            instance: ${spring.application.name}:${server.port}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}
