server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: monster-service
  config:
    import: optional:configserver:http://localhost:8888
